# Generated by Django 2.2.7 on 2020-07-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20000)),
                ('img', models.CharField(max_length=20000)),
                ('league', models.CharField(max_length=20000)),
                ('games', models.CharField(max_length=20000)),
                ('starts', models.CharField(max_length=20000)),
                ('mins', models.CharField(max_length=20000)),
                ('fgm', models.CharField(max_length=20000)),
                ('fga', models.CharField(max_length=20000)),
                ('fgp', models.CharField(max_length=20000)),
                ('thpm', models.CharField(max_length=20000)),
                ('thpa', models.CharField(max_length=20000)),
                ('thpp', models.CharField(max_length=20000)),
                ('twpm', models.CharField(max_length=20000)),
                ('twpa', models.CharField(max_length=20000)),
                ('twpp', models.CharField(max_length=20000)),
                ('efgp', models.CharField(max_length=20000)),
                ('ftm', models.CharField(max_length=20000)),
                ('fta', models.CharField(max_length=20000)),
                ('ftp', models.CharField(max_length=20000)),
                ('orb', models.CharField(max_length=20000)),
                ('drb', models.CharField(max_length=20000)),
                ('trb', models.CharField(max_length=20000)),
                ('ast', models.CharField(max_length=20000)),
                ('stl', models.CharField(max_length=20000)),
                ('blk', models.CharField(max_length=20000)),
                ('tov', models.CharField(max_length=20000)),
                ('fouls', models.CharField(max_length=20000)),
                ('pts', models.CharField(max_length=20000)),
                ('awards', models.CharField(max_length=20000)),
            ],
        ),
    ]
