# Generated by Django 3.1 on 2020-12-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='nfl_player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20000)),
                ('pos', models.CharField(max_length=20000)),
                ('img', models.CharField(max_length=20000)),
                ('comp', models.CharField(max_length=20000)),
                ('att', models.CharField(max_length=20000)),
                ('pyrd', models.CharField(max_length=20000)),
                ('ptd', models.CharField(max_length=20000)),
                ('intt', models.CharField(max_length=20000)),
                ('rate', models.CharField(max_length=20000)),
                ('sacked', models.CharField(max_length=20000)),
                ('lyrd', models.CharField(max_length=20000)),
                ('tar', models.CharField(max_length=20000)),
                ('rec', models.CharField(max_length=20000)),
                ('yards', models.CharField(max_length=20000)),
                ('td', models.CharField(max_length=20000)),
                ('rush', models.CharField(max_length=20000)),
                ('ryrd', models.CharField(max_length=20000)),
                ('rtd', models.CharField(max_length=20000)),
                ('ret', models.CharField(max_length=20000)),
                ('ktd', models.CharField(max_length=20000)),
                ('tack', models.CharField(max_length=20000)),
                ('ast', models.CharField(max_length=20000)),
                ('sacks', models.CharField(max_length=20000)),
                ('qbh', models.CharField(max_length=20000)),
                ('itrc', models.CharField(max_length=20000)),
                ('iyrd', models.CharField(max_length=20000)),
                ('itd', models.CharField(max_length=20000)),
                ('pd', models.CharField(max_length=20000)),
                ('fum', models.CharField(max_length=20000)),
                ('fl', models.CharField(max_length=20000)),
                ('ff', models.CharField(max_length=20000)),
                ('fr', models.CharField(max_length=20000)),
                ('fyrd', models.CharField(max_length=20000)),
                ('ftd', models.CharField(max_length=20000)),
            ],
        ),
    ]
